[package]

name = "doubly"
version = "1.1.2"
authors = ["Bradley Garagan <bradgaragan@gmail.com>"]
description = "Doubly linked lists in rust"
homepage = "https://github.com/marchelzo/doubly"
keywords = ["container", "list", "linked"]
license = "MIT"

[dependencies]
clippy = "0.0.112"
